Repository swetadash0610/Tindog-website, pull requests merged in 2020-10, with the labels that each got.

#1 Changed the css
  css/styles.css
  index.html
Labels: hacktoberfest

#2 Update styles.css
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#3 Changed Colors
  css/styles.css
Labels: hacktoberfest-accepted

#4 Changed Background Colors
  css/styles.css
Labels: hacktoberfest-accepted

#5 minor modification
  css/styles.css
Labels: hacktoberfest-accepted

#6 some modification
  css/styles.css
Labels: hacktoberfest-accepted

#8 content change
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#9 content change 2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#10 copyright changes
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#11 some padding changes
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted
